### ISSUE TITLE
Upgrade Feathers to v5

### ISSUE THREAD

**Issue by claustres** [weacast/weacast#4]
Refer to https://crow.docs.feathersjs.com/guides/migrating.html & https://dove.docs.feathersjs.com/guides/migrating.html. The most challenging part will probably be authentication management.

**Comment by daffl** [comment]
Just to confirm, Weacast doesn't use authentication-management correct? I've also had reports that the current official version does work with v5.

**Comment by claustres** [comment]
Weacast does not use it.
