### ISSUE TITLE
Migrate docs to vitepress

### ISSUE THREAD

**Issue by claustres** [weacast/weacast#57]
As VuePress has entered maintenance mode.

**Comment by vimalJD** [comment]
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by claustres** [comment]
Hi, yes this project is still ongoing, we will be glad to welcome a pull request on the VitePress migration. Let me know if you'd like to start it on your own so that we don't work on it in the coming days.
