### ISSUE TITLE
wecast proxy configuration 

### ISSUE THREAD

**Issue by 0neTX** [weacast/weacast#70]
### Steps to reproduce

When I try to run the wecast docker container together with a gfs loader I always get the same error connecting to noaa.gov:

`2023-11-10 10:49:20 error: Could not update gfs-world/temperature forecast at 2023-11-11T15:00:00Z for run 2023-11-09T12:00:00Z
2023-11-10 10:49:20 error: getaddrinfo EAI_AGAIN nomads.ncep.noaa.gov
2023-11-10 10:49:28 error: Could not download gfs-world/u-wind forecast at 2023-11-11T18:00:00Z for run 2023-11-10T06:00:00Z getaddrinfo EAI_AGAIN nomads.ncep.noaa.gov`

I have verified that my computer has a connection to noaa.gov but we are using a proxy to connect to the Internet.
I've tried to configure the proxy with the usual Linux environment variables 'HTTP_PROXY'

### Expected behavior
Connect and download data from noaa.gov

### Actual behavior
I'm using this docker-compose: 

```
version: '2'

services:
  weacast-api:
    build: .
    container_name: weacast-api
    image: weacast/weacast-api
    links:
      - weacast-mongodb:mongodb
    ports:
      - 8081:8081
    networks:
      - weacast
    environment:
      - VIRTUAL_HOST=desktop123
      - VIRTUAL_PORT=8081
      - DB_URL=mongodb://mongodb:27017/weacast
      - LOADERS=gfs
      - LOG_LEVEL
      - DEBUG
      - HTTP_PROXY=http://user:password@internet.domain.com:3412
      - HTTPS_PROXY=http://user:password@internet.domain.com:3412
      - NO_PROXY=localhost, 127.0.0.1
      - http_proxy=http://user:password@internet.domain.com:3412
      - https_proxy=http://user:password@internet.domain.com:3412
      - no_proxy=localhost, 127.0.0.1      
  weacast-mongodb:
    container_name: weacast-mongodb
    image: mongo:3
    ports:
      - 27017:27017
    volumes:
      - weacast_mongodb:/data/db
    networks:
      - weacast
  weacast-gfs-world:        
    container_name: weacast-gfs-world
    image: weacast/weacast-gfs:world-latest
    links:
      - weacast-mongodb:mongodb
    networks:
      - weacast
    environment:
      - DB_URL=mongodb://mongodb:27017/weacast
      - HTTP_PROXY=http://user:password@internet.domain.com:3412
      - HTTPS_PROXY=http://user:password@internet.domain.com:3412
      - NO_PROXY=localhost, 127.0.0.1
      - http_proxy=http://user:password@internet.domain.com:3412
      - https_proxy=http://user:password@internet.domain.com:3412      

volumes:
  weacast_mongodb:

networks:
  weacast:

```

### System configuration

Docker Desktop 4.21.1

**Comment by claustres** [comment]
Hi, thanks for your interest and feedback. As under the hood weacast is using [request](https://github.com/request/request) maybe you can first try to [debug](https://github.com/request/request#debugging) and get more information about the problem. Typically you can set this in your Docker environment `NODE_DEBUG=request`. By the way, the standard proxy environment variables should work: https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables.

Is your proxy located on your own local host or on a remote network/internet server ? Indeed, based on my experience, Docker Desktop often mess up with the network. Also, a container cannot access `localhost` directly except if using host network mode or the internal docker host `host.docker.internal`.
